# Generated by Django 5.0.4 on 2026-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=100, unique=True)),
                ('ruc', models.CharField(blank=True, help_text='RUC del proveedor', max_length=11, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=15)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del proveedor')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
