# Generated by Django 5.0.4 on 2026-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado_sunat',
            field=models.CharField(default='HABIDO / ACTIVO', help_text='Estado del RUC en SUNAT', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas u observaciones comerciales', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona_contacto',
            field=models.CharField(blank=True, help_text='Persona de contacto / Ejecutivo', max_length=100, null=True),
        ),
    ]
