# Generated by Django 5.0.4 on 2026-05-09 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_transferenciadetalle_fecha_vencimiento'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_final_efectivo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_final_yape_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_final_plin_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_esperado_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_esperado_yape', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_esperado_plin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mercado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.caja'),
        ),
    ]
