# Generated by Django 5.0.4 on 2026-05-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_monto_recibido_venta_num_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
