# Generated by Django 5.0.4 on 2026-06-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_unidadproducto_delete_lotevencimiento_and_more'),
        ('ventas', '0006_venta_costo_total_venta_estado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('mercado', 'tipo_comprobante', 'serie', 'numero')},
        ),
    ]
