# Generated by Django 5.0.4 on 2026-07-22 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_producto_unidad_medida'),
        ('ventas', '0008_venta_descuento_ventadetalle_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['mercado', '-fecha_hora'], name='ventas_vent_mercado_6b8b21_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha_hora'], name='ventas_vent_fecha_h_1f0197_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['mercado', 'estado'], name='ventas_vent_mercado_94602e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['mercado', 'metodo_pago'], name='ventas_vent_mercado_f21008_idx'),
        ),
    ]
