# Generated by Django 5.0.4 on 2026-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de adquisición del producto.', max_digits=10),
        ),
    ]
