# Generated by Django 5.0.4 on 2026-05-07 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_mercado_categoria_mercado_producto_mercado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_nuevo', models.IntegerField()),
                ('referencia_tipo', models.CharField(blank=True, help_text='Tipo de documento: Compra, Venta, Ajuste, etc.', max_length=50)),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID del documento de referencia', null=True)),
                ('referencia_detalle', models.CharField(blank=True, help_text='Descripción adicional del movimiento', max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_kardex', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='inventario__product_72dedb_idx'), models.Index(fields=['mercado', 'fecha'], name='inventario__mercado_3d938c_idx')],
            },
        ),
    ]
