# Generated by Django 5.0.4 on 2026-05-08 01:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_kardex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('ENTRADA_TRANSFERENCIA', 'Entrada por Transferencia'), ('SALIDA_TRANSFERENCIA', 'Salida por Transferencia')], max_length=30),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_TRANSITO', 'En Tránsito'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='EN_TRANSITO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('mercado_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='inventario.mercado')),
                ('mercado_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='inventario.mercado')),
                ('usuario_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='inventario.producto')),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='inventario.producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.transferencia')),
            ],
        ),
    ]
