# Generated by Django 5.0.4 on 2026-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_kardex_tipo_movimiento_transferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras para identificación rápida.', max_length=50, null=True),
        ),
    ]
