# Generated by Django 5.0.4 on 2026-05-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_codigo_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Lote de Vencimiento',
                'verbose_name_plural': 'Lotes de Vencimiento',
                'ordering': ['fecha_vencimiento'],
                'indexes': [models.Index(fields=['producto', 'fecha_vencimiento', 'activo'], name='inventario__product_6b34ce_idx')],
            },
        ),
    ]
