# Generated by Django 5.0.4 on 2026-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_stock_minimo_producto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciadetalle',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del lote transferido.', null=True),
        ),
    ]
