# Generated by Django 5.0.4 on 2026-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_transferenciadetalle_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercado',
            name='ruc',
            field=models.CharField(blank=True, help_text='Número de RUC de la sucursal.', max_length=11, null=True),
        ),
    ]
