# Generated by Django 5.0.4 on 2026-05-30 08:48

import django.db.models.deletion
from django.db import migrations, models


def migrar_lotes_a_unidades(apps, schema_editor):
    LoteVencimiento = apps.get_model('inventario', 'LoteVencimiento')
    UnidadProducto = apps.get_model('inventario', 'UnidadProducto')
    Producto = apps.get_model('inventario', 'Producto')

    for lote in LoteVencimiento.objects.filter(activo=True, cantidad_actual__gt=0):
        producto = lote.producto
        um = producto.unidad_medida
        cantidad = lote.cantidad_actual

        if um in ('UND', 'PAQ'):
            total = int(cantidad)
            records = [
                UnidadProducto(
                    producto_id=lote.producto_id,
                    mercado_id=lote.mercado_id,
                    fecha_vencimiento=lote.fecha_vencimiento,
                    cantidad=1,
                    estado='disponible',
                    fecha_creacion=lote.fecha_creacion,
                )
                for _ in range(total)
            ]
            UnidadProducto.objects.bulk_create(records)
        else:
            UnidadProducto.objects.create(
                producto_id=lote.producto_id,
                mercado_id=lote.mercado_id,
                fecha_vencimiento=lote.fecha_vencimiento,
                cantidad=cantidad,
                estado='disponible',
                fecha_creacion=lote.fecha_creacion,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_mercado_ruc'),
        ('ventas', '0006_venta_costo_total_venta_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, help_text='1 para unidades enteras, fracción para decimales', max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('daniado', 'Dañado'), ('perdida', 'Pérdida')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='inventario.producto')),
                ('venta_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='ventas.ventadetalle')),
            ],
            options={
                'verbose_name': 'Unidad de Producto',
                'verbose_name_plural': 'Unidades de Producto',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.RunPython(migrar_lotes_a_unidades),
        migrations.DeleteModel(
            name='LoteVencimiento',
        ),
        migrations.AddIndex(
            model_name='unidadproducto',
            index=models.Index(fields=['producto', 'fecha_vencimiento', 'estado'], name='inventario__product_2c3c40_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadproducto',
            index=models.Index(fields=['producto', 'mercado', 'estado', 'fecha_vencimiento'], name='inventario__product_ea9315_idx'),
        ),
    ]
