# Generated by Django 5.0.4 on 2026-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_unidadproducto_delete_lotevencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('PAQ', 'Paquete'), ('CAJ', 'Caja'), ('BOL', 'Bolsa')], default='UND', max_length=10),
        ),
    ]
