# Generated by Django 5.0.4 on 2026-07-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, help_text='Data URI Base64 persistente para almacenamiento en nube / BD.', null=True),
        ),
    ]
