# Generated by Django 5.0.4 on 2026-05-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha en que vence este lote de productos.', null=True),
        ),
    ]
