# Generated by Django 5.0.4 on 2026-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_usuario_alter_detallecompra_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='Número de comprobante de compra', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='serie_comprobante',
            field=models.CharField(blank=True, help_text='Serie del comprobante de compra (ej: F001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_comprobante',
            field=models.CharField(default='FACTURA', help_text='FACTURA, BOLETA, GUIA_REMISION, TICKET', max_length=50),
        ),
    ]
