# Generated by Django 5.0.4 on 2026-07-22 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_numero_comprobante_compra_observaciones_and_more'),
        ('proveedores', '0002_proveedor_estado_sunat_proveedor_notas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['-fecha'], name='compras_com_fecha_f13a73_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor', '-fecha'], name='compras_com_proveed_9a1c87_idx'),
        ),
    ]
